# Generated by Django 4.1.1 on 2022-09-14 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 14, 15, 40, 32, 276187, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
